app = "forex-bot"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  FIX_HOST = "demo-us-eqx-01.p.c-trader.com"
  FIX_QUOTE_PORT = "5211"
  FIX_TRADE_PORT = "5212"
  FIX_USE_SSL = "true"
  FIX_SENDER_COMP_ID = "demo.pepperstone.5294375"
  FIX_TARGET_COMP_ID = "cServer"
  FIX_ACCOUNT = "5294375"
  FIX_SENDER_SUB_ID = "5294375"
  FIX_BALANCE_USD = "200"
  FIREBASE_ENABLED = "false"

[env.secrets]
  FIX_PASSWORD = ""
